### ISSUE TITLE
OPEN BROWER リンクからトゥートを見ようとするとドメインが正しくない

### ISSUE THREAD

**Issue by Hikali-47041** [takusan23/Kaisendon-VSCode#1]
firends.nico以外のインスタンスからの投稿ですが、どうやらURLのインスタンスががfriends.nicoになってしまいます。
間違っていたらごめんなさい。

![image](https://user-images.githubusercontent.com/34558365/83344474-6243c900-a342-11ea-8102-f000198feb84.png)

**Comment by Hikali-47041** [comment]
あとブラウザのスペルはBrowserです。

**Comment by takusan23** [comment]
friends.nicoで開く問題は私のミスですね。直しておきました。
![image](https://user-images.githubusercontent.com/32033405/83345994-cc189e80-a353-11ea-9e41-9236b32589ce.png)
